### ISSUE TITLE
It doesn't work on my iPhone 6+

### ISSUE THREAD

**Issue by mrgoonie** [myflashlab/videoPlayer-ANE#10]
I've done exactly the same with the example:

```
import com.myflashlab.air.extensions.player.VideoPlayer;
import com.myflashlab.air.extensions.player.VideoType;
import flash.events.MouseEvent;

var player:VideoPlayer = new VideoPlayer();

playBtn.addEventListener(MouseEvent.CLICK, function(e:MouseEvent){
	player.play("http://myflashlabs.com/showcase/Bully_Scholarship_Edition_Trailer.mp4", VideoType.ON_LINE);
})
```

But when I press on the button, it show the native player with nothing.. all's black without any errors, so I don't know where to go next...

Tested on iPhone 6+ (iOS 10.0.2) - AIR SDK 23.0.0.257

**Comment by mrgoonie** [comment]
Hello.. is anybody there?

**Comment by myflashlab** [comment]
Well, of course. the video address you have used is located on **http** and iOS 9+ needs https addresses only. If you still want to use http addresses, you need to add the following to your AIR manifest file:

```xml
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```
This page will have more details on a related problem: http://stackoverflow.com/questions/30739473/nsurlsession-nsurlconnection-http-load-failed-on-ios-9

**Comment by mrgoonie** [comment]
Solved. Thanks!

I think it should be put in the documentation as a need..
