### ISSUE TITLE
videoPlayerExtension is not a valid ANE file

### ISSUE THREAD

**Issue by mwallon** [myflashlab/videoPlayer-ANE#12]
Hi,
I get the above message when trying out your extension.
Air 24.0.0.177 for ios
Animate CC 16.0.0.112

Best regards!
/magnus

**Comment by myflashlab** [comment]
This might have happened because of a known bug in AIR 24. We just released V3.0.1 which is actually compiled with AIR 24. It should work fine now. Please update yourself and test it in your project and let us know how it goes.

**Comment by mwallon** [comment]
Hi,
Now I get this error instead:

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MyFlashLabsClass", referenced from:
      objc-class-ref in libcom.myflashlab.air.extensions.videoPlayer.a(ExtentionMoviePlayer.o)
ld: symbol(s) not found for architecture arm64
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_MyFlashLabsClass", referenced from:
      objc-class-ref in libcom.myflashlab.air.extensions.videoPlayer.a(ExtentionMoviePlayer.o)
ld: symbol(s) not found for architecture armv7

/magnus

**Comment by myflashlab** [comment]
As explained [here](https://github.com/myflashlab/videoPlayer-ANE#changelog) you need to include the latest overrideAir dependency to your project and that error message will go away.
