### ISSUE TITLE
Cannot build apk from this FD project

### ISSUE THREAD

**Issue by alfredtony** [myflashlab/videoPlayer-ANE#13]
Dear dev team,
I have updated this VideoPlayerANE to 3.0 (from purchased older version) and it can not call the native player when I run app from real device. It works fine with your demo apk. Can you reupdate this FD project because exported apk can not play video

**Comment by myflashlab** [comment]
We have just released V3.0.1. Update yourself and see ho wit goes. Let me know if you have any problem with it?

**Comment by myflashlab** [comment]
please let us know if you still have more information about this issue?

**Comment by alfredtony** [comment]
My problem was solved on new version ane. Thanks for suppoting (Y)
