### ISSUE TITLE
This File Cant play error in android mobile

### ISSUE THREAD

**Issue by saliks** [myflashlab/videoPlayer-ANE#17]
Hi,

I am trying your Demo version videoplayer ane  and i follow each and every step to play my video on sdcard

I published my app by attching extentions and xml  files and I also linked my video in packaged file but on mobile when I launch app it shows "This file cant play"

Please let me know how can I resolve this

Thanks

**Comment by myflashlab** [comment]
1. Are you sure you are addressing to the file correctly?
2. If you are using latest AIR SDK with Android target 23+ you need to have asked for the [Storage Permission](https://github.com/myflashlab/PermissionCheck-ANE/). Have you done that?
3. Do you have a error log from AndroidStudio logcat to send to us?

**Comment by myflashlab** [comment]
Please update us about how it goes?

**Comment by saliks** [comment]
Hi,

When I add Permission Check ane I get a error ‘Name space invalid’.

**Comment by myflashlab** [comment]
check this answer: https://github.com/myflashlab/PermissionCheck-ANE/issues/17#issuecomment-304681479

**Comment by torchofjoy** [comment]
Hey,
When I add the PermissionCheck I get this error: The content cannot be loaded because there was a problem loading an extension: Error: Extension namespace is invalid for C:\Users\...\AppData\Local\Temp\Tmp_ANE_File_Unzipped_Packages\permissionCheck.ane

**Comment by myflashlab** [comment]
@torchofjoy did you opened the address we linked in the previous post? https://github.com/myflashlab/videoPlayer-ANE/issues/17#issuecomment-304681800

@saliks Please let us know if the issue is solved?

**Comment by torchofjoy** [comment]
I still have the problem. I'm using animate cc 2017 and AIR 23.

**Comment by torchofjoy** [comment]
@myflashlab I bought The ane, now I need help but you take too much time to answer. Did I lose my money?

**Comment by myflashlab** [comment]
Ok, try AIR SDK 25 and make sure you are using the latest version of dependency ANEs. Let us knoq if you still have any trouble? Make sure to update your .xml manifest AIR SDK version to 25 also. refer to the link I posted above.

**Comment by torchofjoy** [comment]
It's ok now, Thank you @myflashlab
