### ISSUE TITLE
Demo setup - Class not found when running app on device

### ISSUE THREAD

**Issue by shapevoid2014** [myflashlab/videoPlayer-ANE#2]
Hi Im considering purchasing but want to confirm requirements for use on iOS. This page (https://github.com/myflashlab/videoPlayer-ANE) states no air manifest extensionID's are required to use the extension, so simply including the ANE in my IntelliJIDEA project should suffice? Im running into an error stating the class could not be found when the app runs on the device. Im not sure if its an IDE issue, but just wanted to confirm the extensionID is not required in the manifest xml file?

Cheers
J

**Comment by myflashlab** [comment]
Of course it is needed, sorry that we have missed mentioning it. Please
download the sample project and look into its manifest xml file and there
you will see everything you need to run the extension.

On Thursday, July 16, 2015, shapevoid2014 <notifications@github.com> wrote:

> Hi Im considering purchasing but want to confirm requirements for use on
> iOS. This page (https://github.com/myflashlab/videoPlayer-ANE) states no
> air manifest extensionID's are required to use the extension, so simply
> including the ANE in my IntelliJIDEA project should suffice? Im running
> into an error stating the class could not be found when the app runs on the
> device. Im not sure if its an IDE issue, but just wanted to confirm the
> extensionID is not required in the manifest xml file?
>
> Cheers
> J
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/videoPlayer-ANE/issues/2>.
>


-- 
Sent from iPhone
