### ISSUE TITLE
Show Album Artwork for MP3

### ISSUE THREAD

**Issue by jonathonpitman** [myflashlab/videoPlayer-ANE#27]
The player opens MP3's perfectly but doesnt show the MP3's embedded album art. Instead it shows a giant quicktime logo. If I tap on the airplay icon I can see the album art in that menu. 

Is there any way to get it to show the album art of an MP3 that is playing ?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
