### ISSUE TITLE
No resource found that matches the given name

### ISSUE THREAD

**Issue by jonathonpitman** [myflashlab/videoPlayer-ANE#28]
Error: No resource found that matches the given name (at 'resource' with value '@xml/video_player_ane_provider_paths').

```xml
<!--
				Change [your-app-id] to your own applicationID but keep
				".provider" at the end. [your-app-id].provider
			-->
			<provider
				android:name="com.myflashlabs.videoPlayer.AneVideoProvider"
				android:authorities="air.com.applauz.blameme.provider"
				android:exported="false"
				android:grantUriPermissions="true">
				<meta-data
					android:name="android.support.FILE_PROVIDER_PATHS"
					android:resource="@xml/video_player_ane_provider_paths"/>
			</provider>


			<activity>
				<intent-filter>
					<action android:name="android.intent.action.MAIN" />
					<category android:name="android.intent.category.LAUNCHER" />
				</intent-filter>
				<intent-filter>
					<action android:name="android.intent.action.VIEW" />
					<category android:name="android.intent.category.BROWSABLE" />
					<category android:name="android.intent.category.DEFAULT" />
				</intent-filter>
			</activity>
```

**Comment by myflashlab** [comment]
this is the latest feature we have added to the ANE and it works fine in all our tests. please make sure you have the latest ANE and also the latest AndroidSupport ANE.

**Comment by jonathonpitman** [comment]
Got all the latest of everything ... now the error is:

`dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/adobe/air/ActivityResultCallback;`

**Comment by jonathonpitman** [comment]
Attached

[scanner-app.xml.zip](https://github.com/myflashlab/videoPlayer-ANE/files/2310428/scanner-app.xml.zip)

**Comment by jonathonpitman** [comment]
Attached
[App-app.xml.zip](https://github.com/myflashlab/videoPlayer-ANE/files/2310437/App-app.xml.zip)

**Comment by myflashlab** [comment]
Thanks for the file but we noticed that you are using the ANEs from many different providers. This makes it hard to debug. Please remove other ones and see if the error happens again? There's a high chance of ANE conflicts which we can't predict based on how other ANEs are constructed.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
