### ISSUE TITLE
play youtube video,some video got error 10102

### ISSUE THREAD

**Issue by peter-chen-tonton** [myflashlab/videoPlayer-ANE#29]
Hi,

I am trying your Demo version videoplayer ane to play video from youtube on android device, and most of them works fine.
But for some videos,it says: can't play the video (-10102)

for example:
_ytParser.parse("https://www.youtube.com/watch?v=h7_Z_U1UUiI");	

or
_ytParser.parse("https://www.youtube.com/watch?v=rBwmk2zzIy8");		

Please let me know how can I resolve this

Note: I use flash builder 4.6

Thanks

**Comment by myflashlab** [comment]
please note that playing youtube videos has nothing to do with the ANE. actually we have a project here for parsing youtube urls https://github.com/myflashlab/AS3-youtube-parser-video-link/ So, considering that this question is not related to the ANE, I have to close it.

about some videos not being played, you must know that the current method of parsing youtube videos is limited to only those videos which are public and have no age or country restrictions. If a video has ANY kind of restriction, its url will not be parsed. There's nothing we can do about that.
