### ISSUE TITLE
works with starling and fms

### ISSUE THREAD

**Issue by williamshum** [myflashlab/videoPlayer-ANE#3]
Hi,

can this videoPlayer-ANE plays rtmp video sources, such as live application. In addition, can the video display under starling displayibject?

William

**Comment by myflashlab** [comment]
It works with Starling projects, yes. But it only works with local and
online video files. No streaming in this version

On Friday, July 24, 2015, williamshum <notifications@github.com> wrote:

> Hi,
>
> can this videoPlayer-ANE plays rtmp video sources, such as live
> application. In addition, can the video display under starling
> displayibject?
>
> William
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/videoPlayer-ANE/issues/3>.
>


-- 
Sent from iPhone
