### ISSUE TITLE
UNEXPECTED TOP-LEVEL EXCEPTION

### ISSUE THREAD

**Issue by jonathonpitman** [myflashlab/videoPlayer-ANE#30]
I've updated to the latest of everything and when trying to publish for Android I get the following error. 

`dx tool failed: UNEXPECTED TOP-LEVEL EXCEPTION: java.lang.IllegalArgumentException: already added: Lcom/adobe/air/ActivityResultCallback;`

Publishes fine for iOS

**Comment by myflashlab** [comment]
let's continue on https://github.com/myflashlab/videoPlayer-ANE/issues/28#issuecomment-412517511
