### ISSUE TITLE
Is there a way to play YouTube streams?

### ISSUE THREAD

**Issue by sairope** [myflashlab/videoPlayer-ANE#31]
Do you know a way to get a direct link to a stream and play it in an air app? Does any of your solutions allow that?

**Comment by myflashlab** [comment]
this is what we have for parsing youtube links: https://github.com/myflashlab/AS3-youtube-parser-video-link

**Comment by sairope** [comment]
Yes, this works perfectly for normal YT videos, but not for streams sadly.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
