### ISSUE TITLE
Is there a way to play local files outside the cache directory on Android?

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/videoPlayer-ANE#32]
Hi there. I need to play video files stored in the document directory, or anywhere already in the device.
Cache directory can only download files or create them, it is not very useful.
Is there a way to reference i.e. user folder?
thank you

**Comment by myflashlab** [comment]
More details found in [this post](https://github.com/myflashlab/videoPlayer-ANE/issues/23#issuecomment-432559252)

However, it's worthy to mention that there is a bug in AIR SDK that prevents us from using a provider like below.

```xml
<paths>
    <external-path name="external_files" path="." />
</paths>
```

We tested different options and at least the cache directory is working fine! We will be submitting a bug report to Adobe soon so they know the problem and hopefully add support for that but before we submit the bug, we are still testing and investigating if we can create a workaround for this. If we couldn't find any solution, we will let Adobe know about it.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
