### ISSUE TITLE
YouTube videos no longer loading

### ISSUE THREAD

**Issue by jonathonpitman** [myflashlab/videoPlayer-ANE#33]
Everything was working. Not sure if its because of iOS 12.  I've updated to your latest ANE's and am using AIR 31. 

Any ideas how to fix ?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
