### ISSUE TITLE
Doesn't run on IOS 8.4

### ISSUE THREAD

**Issue by NQX** [myflashlab/videoPlayer-ANE#4]
My App runs fine on Android, but on IOS the Video Player crashes immediately. Even the Demo Project doesn't run fine. Ipad Air 2.

**Comment by myflashlab** [comment]
in our tests, it runs fine with iOS 8.4 tell me if you have this problem on iPad Air 2 only? does it work on other devices?

**Comment by NQX** [comment]
It runs without problems on my Ipad 2.
I have noticed, that it runs, when the Video is streamed via youtube or web.

**Comment by myflashlab** [comment]
Make sure you are addressing the local file address correctly? it should be fine
