### ISSUE TITLE
Detect end of the video

### ISSUE THREAD

**Issue by nmarti** [myflashlab/videoPlayer-ANE#5]
Hi, I just purchased the full version of this extension.

How can I detect the end of the video, so I can restart the background music of the app (on iOS)?

Thanks.

**Comment by myflashlab** [comment]
this video player ANE is playing the video on device's native player detached from the app. on Android, you can listen to the app active/deactive status but in iOS those events won't fire. 

we have developed the surface video player https://github.com/myflashlab/surfaceVideoPlayer-ANE which the video will be embeded inside the air app and that ane will dispatch video states as soon as they change.
