### ISSUE TITLE
What's this error ?

### ISSUE THREAD

**Issue by KangPrince** [myflashlab/videoPlayer-ANE#6]
Hi,
I build a test app with videoPlayer-ANE and Flash Builder.
But, I have an error massage.
1046: Type was not found or was not a compile-time constant:VideoPlayer.
What's that?
Regards.

**Comment by myflashlab** [comment]
Are you trying to run on a simulator? please use a real device instead.
another thing to check is if you are using the latest AdobeAir version?
And also make sure you have correctly embeded the ANE into the manifest?

**Comment by KangPrince** [comment]
Would you tell me the error ?
connecting to youtube...
Error: could not connect to server!

Regards.

**Comment by myflashlab** [comment]
you're using https://github.com/myflashlab/AS3-youtube-parser-video-link?

**Comment by KangPrince** [comment]
Yes, I'm using the AS files.

**Comment by KangPrince** [comment]
function toPlayVideoIntentYouTube(e:MouseEvent):void {
	trace("connecting to youtube...");
	trace(_ytParser);   // -> null
	if(!_ytParser) _ytParser = new YouTubeLinkParser();
	trace(_ytParser);   // -> [object YouTubeLinkParser]
	_ytParser.addEventListener(YouTubeLinkParserEvent.COMPLETE, onComplete);
	_ytParser.addEventListener(YouTubeLinkParserEvent.ERROR, onError);
	_ytParser.parse("https://www.youtube.com/watch?v=QowwaefoCec");
}
-> Error: could not connect to server!

**Comment by myflashlab** [comment]
we can't duplicate this problem! trying the code in https://github.com/myflashlab/AS3-youtube-parser-video-link is just working fine.
