### ISSUE TITLE
Error when packaging application

### ISSUE THREAD

**Issue by tholhubner** [myflashlab/videoPlayer-ANE#8]
I am new to using your ANE, but everything has been great so far. I am not sure if this issue with your ANE is something that you have seen before or not, it just started happening a few days ago, and was not happening at all before hand. Here is the error message I get when trying to build to the iOS simulator, which I had no problem doing earlier this week: Error occurred while packaging the application:
Warning: Using default implementation for native extension 'com.myflashlab.air.extensions.videoPlayer'

The only change that I have made is switching to AIR 22 beta, but that was done after this issue started occurring. Any help would be greatly appreciated.

**Comment by myflashlab** [comment]
Hi @tholhubner Actually you should not try to run the ANE on a simulator. run it on a real device or comment it out when building on the simulator.
