### ISSUE TITLE
Cannot access a property or method of a null object reference

### ISSUE THREAD

**Issue by tanhzero** [myflashlab/videoPlayer-ANE#9]
I just create a Air mobile project and use your simple code and get an error:

TypeError: Error #1009: Cannot access a property or method of a null object reference.
    at com.myflashlab.air.extensions.player::Android()
    at com.myflashlab.air.extensions.player::VideoPlayer()

Please send your help

**Comment by myflashlab** [comment]
@tanhzero when you receive a null reference it means that you have not correctly embedded the ANE in your project OR you might be running on a simulator. You need to run your project on a real device.

You may watch the following videos to help you in the process of implementing the ANEs: https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

Besides that, we have developed a free tool called the [ANE inspector](https://github.com/myflashlab/ANE-Inspector-Tool) which you can use to know why the ANE is not working on your project so you can fix the problem.
